### ISSUE TITLE
Crashes when broken symlink is present in project home directory

### ISSUE THREAD

**Issue by jacobmischka** [chuckhendo/project-quick-open#17]
Of course I just deleted the symlink and everything works fine now, but just letting you know. 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.19.3-1-ARCH
**Thrown From**: [project-quick-open](https://github.com/chuckhendo/project-quick-open) package, v0.4.2

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/mischka/projects/bird'

```
At fs.js:807

Error: ENOENT, no such file or directory '/home/mischka/projects/bird'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at /home/mischka/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:60:77
  at /home/mischka/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:95:15
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:00.7 project-quick-open:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "projectHome": "/home/mischka/projects/"
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
color-picker, v1.5.0
compare-files, v0.4.1
file-icons, v1.5.2
highlight-selected, v0.9.1
keybinding-cheatsheet, v0.0.8
language-latex, v0.4.1
language-lua, v0.9.0
language-qml, v0.1.0
minimap, v4.7.4
minimap-color-highlight, v4.1.0
minimap-highlight-selected, v4.2.0
project-quick-open, v0.4.2

# Dev
No dev packages
```

**Comment by chuckhendo** [comment]
This should be fixed in 0.4.4. Please let me know if it isn't!
