### ISSUE TITLE
Uncaught TypeError: Cannot read property 'projectHome' of undefined

### ISSUE THREAD

**Issue by LiLejia** [chuckhendo/project-quick-open#28]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [project-quick-open](https://github.com/chuckhendo/project-quick-open) package, v0.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'projectHome' of undefined

```
At /Users/henry/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:46

TypeError: Cannot read property 'projectHome' of undefined
    at ProjectQuickOpenView.module.exports.ProjectQuickOpenView.getProjectPath (/Users/henry/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:46:42)
    at ProjectQuickOpenView.module.exports.ProjectQuickOpenView.show (/Users/henry/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:65:10)
    at ProjectQuickOpenView.module.exports.ProjectQuickOpenView.toggle (/Users/henry/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:81:14)
    at atom-workspace.<anonymous> (/Users/henry/.atom/packages/project-quick-open/lib/project-quick-open-view.coffee:11:78)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:12.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:10.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 project-quick-open:toggle (div.panels)
  2x -0:10.1.0 editor:log-cursor-scope (atom-text-editor.editor.mini.is-focused)
  2x -0:06.9.0 project-quick-open:toggle (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
project-quick-open, v0.5.0

# Dev
No dev packages
```

**Comment by born4new** [comment]
I just had this error, and what you need to do is to configure your projects base folder in the tool's configuration (CMD + , and go to the plugin config)
